### ISSUE TITLE
ActionUpdateThread.OLD_EDT is deprecated

### ISSUE THREAD

**Issue by igorepst** [arhont375/intellij-thrift#26]
Hello. I just got the following in IntelliJ 2024.1 Ultimate for plugin v. 1.8.1

    com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 
    'com.intellij.plugins.thrift.editor.GoToThriftDefinition' must override `getActionUpdateThread` and chose EDT or BGT. See 
    ActionUpdateThread javadoc. [Plugin: thrift-syntax-fork]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

Please take a look. Thank you in advance

**Comment by wwsc-bos** [comment]
Happens on all 2024.1 IDEs when plugin is enabled. Plugin was updated recently and shows as being compatible with 2024.1 releases. Plugin still works but throws this annoying internal IDE error. I thought I could make it reoccur at will when I opened a thrift file but today when adding this comment, it is much more elusive.
